version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    open-pull-requests-limit: 20
    schedule:
      interval: "daily"
      time: "05:00"
      timezone: "Asia/Tokyo"
    groups:
      tailwindcss:
        patterns:
          - "tailwindcss"
          - "@tailwindcss/*"
  - package-ecosystem: "github-actions"
    directory: "/"
    open-pull-requests-limit: 20
    schedule:
      interval: "daily"
      time: "05:00"
      timezone: "Asia/Tokyo"
