version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    open-pull-requests-limit: 20
    schedule:
      interval: "daily"
      time: "05:00"
      timezone: "Asia/Tokyo"
    groups:
      tailwindcss:
        patterns:
          - "tailwindcss"
          - "@tailwindcss/*"
      react:
        patterns:
          - "react"
          - "react-dom"
          - "@types/react"
          - "@types/react-dom"
      eslint:
        patterns:
          - "eslint"
          - "@eslint/*"
      nextjs:
        patterns:
          - "next"
          - "eslint-config-next"
  - package-ecosystem: "github-actions"
    directory: "/"
    open-pull-requests-limit: 20
    schedule:
      interval: "daily"
      time: "05:00"
      timezone: "Asia/Tokyo"
