name: build

on:
  - pull_request

jobs:
  build:
    runs-on: ${{ matrix.runner }}
    timeout-minutes: 10
    strategy:
      matrix:
        runner: [ubuntu-latest]
        node: [22.20.0]
    name: build on node ${{ matrix.node }} ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v5
      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node }}
      - name: npm ci
        run: npm ci
      - name: build
        run: npm run build
