name: Deploy to Firebase Hosting on cron

on:
  schedule:
    - cron: '0 8 21 * *'

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm ci && npm run build && npm run export
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_IWDD_NET_NEXTJS }}'
          channelId: live
          projectId: iwdd-net-nextjs
